### PR TITLE
JJ photogram industrial 2

### PR DESCRIPTION
**Pull request by jessjno**

### CODE REVIEW

**Review by JoseMDO — APPROVED** [review]
Great job Jess!

**Comment by tluu5** [comment]
Nice job

**Review by tluu5 — COMMENTED** [review]
great job writing the has_many relationships

**Review by tluu5 — COMMENTED** [review]
Like your lines writing the scope past_week and by_likes

**Review by tluu5 — COMMENTED** [review]
Thumbs up for adding default to TRUE

**Review by tluu5 — COMMENTED** [review]
Good catch for putting down the counter_cache: true

**Pull request merged**
